### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by zyf444e668** [BoiHanny/vrcosc-magicchatbox#31]
I never used Spotify before and already it is limited to be listening to music. Some songs aren't on there and i cannot show folks the songs i like to listen to.
I have my songs downloaded to my PC in MP3 or audio formats i can play in Audacity which is what i use daily to listen to music.
If MagicChatBox can project what audio songs i am playing on Audacity, that'd be great! As i said, some songs on Spotify are NOT on there.

**Comment by princepokey** [comment]
i made another issue that's basically requested the same thing, although i use musicbee and foobar2000 instead of audacity.
either way, it still echos that sentiment of streaming *.mp3 / digital audio formats rather than through conventional streaming services.
support for something like that would be greatly appreciated, if possible

**Comment by PercyGuy** [comment]
Some people can use the inbuilt spotify local files feature, to combine songs hosted on spotify and songs on their device. It even syncs between devices. I know why you wouldn't want to do this, because of ads and stuff but i have family premium which makes spotify a bit better. but heck yeah add better medialink support!
