### ISSUE TITLE
Trojen Virus

### ISSUE THREAD

**Issue by DaUnknownSilence** [BoiHanny/vrcosc-magicchatbox#80]
![image](https://github.com/user-attachments/assets/5745a6a3-0f8e-4d14-819f-629fe49e2315)

virus file in latest update

**Comment by Lyrikidionisos** [comment]
First and foremost, MagicChatbox is designed specifically to facilitate communication with the OSC VRChat Server using OSC connections, which are standard protocols for real-time data transfer in various applications. This functionality is not only legitimate but widely used in the gaming and virtual reality communities. The software does not exhibit any behaviors typical of malicious software, such as unauthorized data access, self-replication, or harmful payload delivery.

The flagging of MagicChatbox as a Trojan by certain antivirus tools, such as Jiangmin and Zillya, is likely a result of heuristic analysis. These tools sometimes misidentify safe applications due to their behavior patterns or the way they interact with system resources. This is a common occurrence in the realm of cybersecurity, where legitimate software can be mistakenly categorized as harmful.

Moreover, the creation of a one week old separate account to voice concerns about MagicChatbox raises questions about the motivations behind such actions. 

If you need further explanations please contact our support:
[MagicChatbox Discord](https://discord.gg/magicchatbox)
